# Generated by Django 4.0.6 on 2022-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_thirdparty_wallet_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='signature',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='image_pics'),
        ),
    ]
